// <auto-generated />
using System;
using ISFDyT124.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ISFDyT124.Migrations
{
    [DbContext(typeof(InstitutoDbContext))]
    [Migration("20260605144324_UsuarioRelationships")]
    partial class UsuarioRelationships
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CarreraMateriaUsuario", b =>
                {
                    b.Property<int>("CarreraMateriasCaMaId")
                        .HasColumnType("int");

                    b.Property<int>("UsuariosUsId")
                        .HasColumnType("int");

                    b.HasKey("CarreraMateriasCaMaId", "UsuariosUsId");

                    b.HasIndex("UsuariosUsId");

                    b.ToTable("UsuarioCarreraMateria", (string)null);
                });

            modelBuilder.Entity("ISFDyT124.Models.Asistencia", b =>
                {
                    b.Property<int>("AsId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("AsFecha")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<bool>("AsJustificacion")
                        .HasColumnType("bit");

                    b.Property<bool>("AsPresente")
                        .HasColumnType("bit");

                    b.Property<int?>("MaId")
                        .HasColumnType("int");

                    b.Property<int?>("UsId")
                        .HasColumnType("int");

                    b.HasKey("AsId");

                    b.HasIndex("MaId");

                    b.HasIndex("UsId");

                    b.ToTable("Asistencias");
                });

            modelBuilder.Entity("ISFDyT124.Models.Carrera", b =>
                {
                    b.Property<int>("CaId")
                        .HasColumnType("int");

                    b.Property<string>("CaDenominacion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CaId");

                    b.ToTable("Carreras");
                });

            modelBuilder.Entity("ISFDyT124.Models.CarreraCohorte", b =>
                {
                    b.Property<int>("CaCoId")
                        .HasColumnType("int");

                    b.Property<int>("CaId")
                        .HasColumnType("int");

                    b.Property<int>("CoId")
                        .HasColumnType("int");

                    b.HasKey("CaCoId");

                    b.HasIndex("CaId");

                    b.HasIndex("CoId");

                    b.ToTable("CarreraCohortes");
                });

            modelBuilder.Entity("ISFDyT124.Models.CarreraMateria", b =>
                {
                    b.Property<int>("CaMaId")
                        .HasColumnType("int");

                    b.Property<int>("CaId")
                        .HasColumnType("int");

                    b.Property<int>("MaId")
                        .HasColumnType("int");

                    b.HasKey("CaMaId");

                    b.HasIndex("CaId");

                    b.HasIndex("MaId");

                    b.ToTable("CarreraMaterias");
                });

            modelBuilder.Entity("ISFDyT124.Models.Cohorte", b =>
                {
                    b.Property<int>("CoId")
                        .HasColumnType("int");

                    b.Property<int>("CoAnio")
                        .HasColumnType("int");

                    b.HasKey("CoId");

                    b.ToTable("Cohortes");
                });

            modelBuilder.Entity("ISFDyT124.Models.Materia", b =>
                {
                    b.Property<int>("MaId")
                        .HasColumnType("int");

                    b.Property<int?>("MaCantModulos")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("MaDenominacion")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("MaModalidad")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("MaId");

                    b.ToTable("Materias");
                });

            modelBuilder.Entity("ISFDyT124.Models.Rol", b =>
                {
                    b.Property<int>("RoId")
                        .HasColumnType("int");

                    b.Property<string>("RoDenominacion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RoId");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("ISFDyT124.Models.Usuario", b =>
                {
                    b.Property<int>("UsId")
                        .HasColumnType("int");

                    b.Property<int?>("CaCoId")
                        .HasColumnType("int");

                    b.Property<int>("RoId")
                        .HasColumnType("int");

                    b.Property<string>("UsApellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UsContrasena")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsDni")
                        .HasColumnType("int");

                    b.Property<string>("UsEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsNombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("UsId");

                    b.HasIndex("CaCoId");

                    b.HasIndex("RoId");

                    b.HasIndex("UsDni")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("ISFDyT124.Models.UsuarioRol", b =>
                {
                    b.Property<int>("UsRoId")
                        .HasColumnType("int");

                    b.Property<int>("RoId")
                        .HasColumnType("int");

                    b.Property<int>("UsId")
                        .HasColumnType("int");

                    b.HasKey("UsRoId");

                    b.HasIndex("RoId");

                    b.HasIndex("UsId");

                    b.ToTable("UsuarioRoles");
                });

            modelBuilder.Entity("CarreraMateriaUsuario", b =>
                {
                    b.HasOne("ISFDyT124.Models.CarreraMateria", null)
                        .WithMany()
                        .HasForeignKey("CarreraMateriasCaMaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ISFDyT124.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuariosUsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ISFDyT124.Models.Asistencia", b =>
                {
                    b.HasOne("ISFDyT124.Models.Materia", "Materia")
                        .WithMany("Asistencias")
                        .HasForeignKey("MaId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ISFDyT124.Models.Usuario", "Usuario")
                        .WithMany("Asistencias")
                        .HasForeignKey("UsId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Materia");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ISFDyT124.Models.CarreraCohorte", b =>
                {
                    b.HasOne("ISFDyT124.Models.Carrera", "Carrera")
                        .WithMany("CarreraCohortes")
                        .HasForeignKey("CaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ISFDyT124.Models.Cohorte", "Cohorte")
                        .WithMany("CarreraCohortes")
                        .HasForeignKey("CoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Carrera");

                    b.Navigation("Cohorte");
                });

            modelBuilder.Entity("ISFDyT124.Models.CarreraMateria", b =>
                {
                    b.HasOne("ISFDyT124.Models.Carrera", "Carrera")
                        .WithMany("CarreraMaterias")
                        .HasForeignKey("CaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ISFDyT124.Models.Materia", "Materia")
                        .WithMany("CarreraMaterias")
                        .HasForeignKey("MaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Carrera");

                    b.Navigation("Materia");
                });

            modelBuilder.Entity("ISFDyT124.Models.Usuario", b =>
                {
                    b.HasOne("ISFDyT124.Models.CarreraCohorte", "CarreraCohorte")
                        .WithMany("Usuarios")
                        .HasForeignKey("CaCoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ISFDyT124.Models.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("RoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CarreraCohorte");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("ISFDyT124.Models.UsuarioRol", b =>
                {
                    b.HasOne("ISFDyT124.Models.Rol", "Rol")
                        .WithMany("UsuarioRoles")
                        .HasForeignKey("RoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ISFDyT124.Models.Usuario", "Usuario")
                        .WithMany("UsuarioRoles")
                        .HasForeignKey("UsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ISFDyT124.Models.Carrera", b =>
                {
                    b.Navigation("CarreraCohortes");

                    b.Navigation("CarreraMaterias");
                });

            modelBuilder.Entity("ISFDyT124.Models.CarreraCohorte", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("ISFDyT124.Models.Cohorte", b =>
                {
                    b.Navigation("CarreraCohortes");
                });

            modelBuilder.Entity("ISFDyT124.Models.Materia", b =>
                {
                    b.Navigation("Asistencias");

                    b.Navigation("CarreraMaterias");
                });

            modelBuilder.Entity("ISFDyT124.Models.Rol", b =>
                {
                    b.Navigation("UsuarioRoles");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("ISFDyT124.Models.Usuario", b =>
                {
                    b.Navigation("Asistencias");

                    b.Navigation("UsuarioRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
